# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Db' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 
#frameworks
  use_frameworks!

  # Pods for Db
pod 'SQLite.swift', '~> 0.11.4'
pod 'Alamofire', '~> 4.7'
end
